CREATE OR ALTER PROCEDURE [dbo].[102_UpdateSchool]
    @id INT,
    @agencyId INT,
    @name NVARCHAR(255),
    @startDate DATE = NULL,
    @address NVARCHAR(255),
    @cityId INT,
    @regionId INT,
    @zipCode NVARCHAR(20),
    @latitude FLOAT = NULL,
    @longitude FLOAT = NULL,
    @postalAddress NVARCHAR(255) = NULL,
    @postalCityId INT = NULL,
    @postalRegionId INT = NULL,
    @postalZipCode NVARCHAR(20) = NULL,
    @sameAsPhysicalAddress BIT = NULL,
    @organizationTypeId INT,
    @centerTypeId INT = NULL,
    @nonProfit BIT = NULL,
    @baseYear INT = NULL,
    @renewalYear INT = NULL,
    @educationLevelId INT,
    @operatingDays INT = NULL,
    @kitchenTypeId INT = NULL,
    @groupTypeId INT = NULL,
    @deliveryTypeId INT = NULL,
    @sponsorTypeId INT = NULL,
    @applicantTypeId INT = NULL,
    @residentialTypeId INT = NULL,
    @operatingPolicyId INT = NULL,
    @hasWarehouse BIT = NULL,
    @hasDiningRoom BIT = NULL,
    @administratorAuthorizedName NVARCHAR(255) = NULL,
    @sitePhone NVARCHAR(20) = NULL,
    @extension NVARCHAR(10) = NULL,
    @mobilePhone NVARCHAR(20) = NULL,
    @breakfast BIT = NULL,
    @breakfastFrom TIME = NULL,
    @breakfastTo TIME = NULL,
    @lunch BIT = NULL,
    @lunchFrom TIME = NULL,
    @lunchTo TIME = NULL,
    @snack BIT = NULL,
    @snackFrom TIME = NULL,
    @snackTo TIME = NULL,
    @isActive BIT = NULL,
    @inactiveJustification NVARCHAR(255) = NULL,
    @inactiveDate DATETIME = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @rowsAffected INT;

    UPDATE School
    SET AgencyId = @agencyId,
        Name = @name,
        StartDate = @startDate,
        Address = @address,
        CityId = @cityId,
        RegionId = @regionId,
        ZipCode = @zipCode,
        Latitude = @latitude,
        Longitude = @longitude,
        PostalAddress = @postalAddress,
        PostalCityId = @postalCityId,
        PostalRegionId = @postalRegionId,
        PostalZipCode = @postalZipCode,
        SameAsPhysicalAddress = @sameAsPhysicalAddress,
        OrganizationTypeId = @organizationTypeId,
        CenterTypeId = @centerTypeId,
        NonProfit = @nonProfit,
        BaseYear = @baseYear,
        RenewalYear = @renewalYear,
        EducationLevelId = @educationLevelId,
        OperatingDays = @operatingDays,
        KitchenTypeId = @kitchenTypeId,
        GroupTypeId = @groupTypeId,
        DeliveryTypeId = @deliveryTypeId,
        SponsorTypeId = @sponsorTypeId,
        ApplicantTypeId = @applicantTypeId,
        ResidentialTypeId = @residentialTypeId,
        OperatingPolicyId = @operatingPolicyId,
        HasWarehouse = @hasWarehouse,
        HasDiningRoom = @hasDiningRoom,
        AdministratorAuthorizedName = @administratorAuthorizedName,
        SitePhone = @sitePhone,
        Extension = @extension,
        MobilePhone = @mobilePhone,
        Breakfast = @breakfast,
        BreakfastFrom = @breakfastFrom,
        BreakfastTo = @breakfastTo,
        Lunch = @lunch,
        LunchFrom = @lunchFrom,
        LunchTo = @lunchTo,
        Snack = @snack,
        SnackFrom = @snackFrom,
        SnackTo = @snackTo,
        IsActive = @isActive,
        InactiveJustification = @inactiveJustification,
        InactiveDate = @inactiveDate,
        UpdatedAt = GETDATE()
    WHERE Id = @id;

    SET @rowsAffected = @@ROWCOUNT;
    RETURN @rowsAffected;
END; 