CREATE OR ALTER PROCEDURE [dbo].[102_UpdateSchool]
    @id INT,
    @agencyId INT,
    @name NVARCHAR(255),
    @startDate DATE = NULL,
    @address NVARCHAR(255),
    @cityId INT,
    @regionId INT,
    @zipCode NVARCHAR(20),
    @latitude FLOAT = NULL,
    @longitude FLOAT = NULL,
    @postalAddress NVARCHAR(255) = NULL,
    @postalCityId INT = NULL,
    @postalRegionId INT = NULL,
    @postalZipCode NVARCHAR(20) = NULL,
    @sameAsPhysicalAddress BIT = NULL,
    @organizationTypeId INT,
    @centerTypeId INT = NULL,
    @areaTypeId INT = NULL,
    @nonProfit BIT = NULL,
    @baseYear INT = NULL,
    @renewalYear INT = NULL,
    @operatingFromDate DATE = NULL,
    @operatingToDate DATE = NULL,
    @operatingDaysCalculated INT = NULL,
    @kitchenTypeId INT = NULL,
    @groupTypeId INT = NULL,
    @deliveryTypeId INT = NULL,
    @sponsorTypeId INT = NULL,
    @applicantTypeId INT = NULL,
    @residentialTypeId INT = NULL,
    @operatingPolicyId INT = NULL,
    @hasWarehouse BIT = NULL,
    @hasDiningRoom BIT = NULL,
    @administratorAuthorizedName NVARCHAR(255) = NULL,
    @sitePhone NVARCHAR(20) = NULL,
    @extension NVARCHAR(10) = NULL,
    @mobilePhone NVARCHAR(20) = NULL,
    @breakfast BIT = NULL,
    @breakfastFrom TIME = NULL,
    @breakfastTo TIME = NULL,
    @lunch BIT = NULL,
    @lunchFrom TIME = NULL,
    @lunchTo TIME = NULL,
    @snack BIT = NULL,
    @snackFrom TIME = NULL,
    @snackTo TIME = NULL,
    @dinner BIT = NULL,
    @dinnerFrom TIME = NULL,
    @dinnerTo TIME = NULL,
    @snackNight BIT = NULL,
    @snackNightFrom TIME = NULL,
    @snackNightTo TIME = NULL,
    @communityId INT = NULL,
    @walkersId INT = NULL,
    @siteTypeId INT = NULL,
    @experienceId INT = NULL,
    @reviewResultId INT = NULL,
    @reviewDate DATETIME = NULL,
    @reviewJustification NVARCHAR(500) = NULL,
    @isActive BIT = NULL,
    @inactiveJustification NVARCHAR(255) = NULL,
    @inactiveDate DATETIME = NULL,
    @serviceTime DATETIME = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @rowsAffected INT;

    UPDATE School
    SET AgencyId = @agencyId,
        Name = @name,
        StartDate = @startDate,
        Address = @address,
        CityId = @cityId,
        RegionId = @regionId,
        ZipCode = @zipCode,
        Latitude = @latitude,
        Longitude = @longitude,
        PostalAddress = @postalAddress,
        PostalCityId = @postalCityId,
        PostalRegionId = @postalRegionId,
        PostalZipCode = @postalZipCode,
        SameAsPhysicalAddress = @sameAsPhysicalAddress,
        OrganizationTypeId = @organizationTypeId,
        CenterTypeId = @centerTypeId,
        AreaTypeId = @areaTypeId,
        NonProfit = @nonProfit,
        BaseYear = @baseYear,
        RenewalYear = @renewalYear,
        OperatingFromDate = @operatingFromDate,
        OperatingToDate = @operatingToDate,
        OperatingDaysCalculated = @operatingDaysCalculated,
        KitchenTypeId = @kitchenTypeId,
        GroupTypeId = @groupTypeId,
        DeliveryTypeId = @deliveryTypeId,
        SponsorTypeId = @sponsorTypeId,
        ApplicantTypeId = @applicantTypeId,
        ResidentialTypeId = @residentialTypeId,
        OperatingPolicyId = @operatingPolicyId,
        HasWarehouse = @hasWarehouse,
        HasDiningRoom = @hasDiningRoom,
        AdministratorAuthorizedName = @administratorAuthorizedName,
        SitePhone = @sitePhone,
        Extension = @extension,
        MobilePhone = @mobilePhone,
        Breakfast = @breakfast,
        BreakfastFrom = @breakfastFrom,
        BreakfastTo = @breakfastTo,
        Lunch = @lunch,
        LunchFrom = @lunchFrom,
        LunchTo = @lunchTo,
        Snack = @snack,
        SnackFrom = @snackFrom,
        SnackTo = @snackTo,
        Dinner = @dinner,
        DinnerFrom = @dinnerFrom,
        DinnerTo = @dinnerTo,
        SnackNight = @snackNight,
        SnackNightFrom = @snackNightFrom,
        SnackNightTo = @snackNightTo,
        CommunityId = @communityId,
        WalkersId = @walkersId,
        SiteTypeId = @siteTypeId,
        ExperienceId = @experienceId,
        ReviewResultId = @reviewResultId,
        ReviewDate = @reviewDate,
        ReviewJustification = @reviewJustification,
        IsActive = @isActive,
        InactiveJustification = @inactiveJustification,
        InactiveDate = @inactiveDate,
        ServiceTime = @serviceTime,
        UpdatedAt = GETDATE()
    WHERE Id = @id;

    SET @rowsAffected = @@ROWCOUNT;
    RETURN @rowsAffected;
END; 