-- Agencias Auspiciadoras (Sponsoring Agencies)
CREATE TABLE Agency
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    AgencyStatusId INT NOT NULL,
    CityId INT NOT NULL,
    PostalCityId INT NULL,
    RegionId INT NOT NULL,
    PostalRegionId INT NULL,
    Name NVARCHAR(255) NOT NULL,
    UieNumber INT NOT NULL,
    EinNumber INT NOT NULL,
    SdrNumber INT NOT NULL,
    Address NVARCHAR(255) NOT NULL,
    ZipCode INT NULL,
    PostalAddress NVARCHAR(255) NOT NULL,
    PostalZipCode INT NULL,
    Phone NVARCHAR(20) NOT NULL DEFAULT '',
    Email NVARCHAR(255) NOT NULL DEFAULT '',
    Latitude FLOAT NOT NULL DEFAULT 0,
    Longitude FLOAT NOT NULL DEFAULT 0,
    NonProfit BIT NULL DEFAULT 0,
    FederalFundsDenied BIT NULL DEFAULT 0,
    StateFundsDenied BIT NULL DEFAULT 0,
    OrganizedAthleticPrograms BIT NULL DEFAULT 0,
    RejectionJustification NVARCHAR(MAX) NULL,
    AtRiskService BIT NULL DEFAULT 0,
    ImageURL NVARCHAR(MAX) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    IsListable BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NULL,
    AgencyCode NVARCHAR(50) NULL,
    IsPropietary BIT NULL DEFAULT 0,
    FOREIGN KEY (AgencyStatusId) REFERENCES AgencyStatus(Id),
    FOREIGN KEY (CityId) REFERENCES City(Id),
    FOREIGN KEY (PostalCityId) REFERENCES City(Id),
    FOREIGN KEY (RegionId) REFERENCES Region(Id),
    FOREIGN KEY (PostalRegionId) REFERENCES Region(Id)
);
GO