CREATE TABLE [dbo].[OperatingPolicies]
(
    [Id] INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(255) NOT NULL,
    [NameEN] NVARCHAR(255) NOT NULL,
    [IsActive] BIT NOT NULL,
    [DisplayOrder] INT NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [UpdatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [CreatedBy] NVARCHAR(255) NOT NULL,
    [UpdatedBy] NVARCHAR(255) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id])
);